@port=3000
@baseUrl=http://localhost:{{port}}/api

POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "firstName":"Rahul",
    "middlename":"",
    "lastName":"Niraula",
    "email":"rahul@niraula.com",
    "password":"password"
}

###
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "email":"rahul@niraula.com",
    "password":"password"
}