@port=3000
@baseUrl=http://localhost:{{port}}/api

POST {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{loginResponse.response.body.data.token}}

{
    "firstName":"Rahul",
    "middlename":"",
    "lastName":"Niraula",
    "email":"rahul@niraula.com",
    "password":"password"
}

###
# @name loginResponse
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "email":"rahul@niraula.com",
    "password":"password"
}

###
GET {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{loginResponse.response.body.data.token}}